% Reads data generated by SNR_plot_MLalg.py programs
% creates probability of detection and false alarm plots

addpath('functions')
%addpath('path\to\folder')
fileName = 'results_NB_ED_numerology2_10UsersUnscatteredOldFeatures_15April2021.txt';
fileID = fopen(fileName, 'r');

SNR = -40:1:20;

sizeA = [3, length(SNR)];
A = fscanf(fileID, '%f %f %f', sizeA);
fclose(fileID);

A=A';
P_detection = A(:, 1);
P_false_alarm = A(:,2);
A_SNR = A(:, 3);


hold on
plot(A_SNR, P_detection, 'b-', 'LineWidth', 1)
hold on
plot(A_SNR, P_false_alarm, 'r-', 'LineWidth', 1)
hold on
xlabel('SNR [dB]')
ylabel('Probability [%]')
legend('probability of detection', 'probability of false alarm');