% Reads testing data generated by matlab programs (prog_A_cyclicRes)

%addpath('funkcje')
%addpath('C:\Users\User\Desktop\Habib Resources\Final Year Project\5G Data\Numerology 1\ED_23March_TS80_U5_Unscattered_RescalingRemoved')

SNR = -40:1:20;
P_detection = zeros(size(SNR));
P_false_alarm = zeros(size(SNR));

for SNRind = 1:length(SNR)
    disp(['SNR = ', num2str(SNR(SNRind))])
    if SNR(SNRind)<0
        fileName = ['data_' num2str(abs(SNR(SNRind))) '_test.txt'];
    else
        fileName = ['data' num2str(abs(SNR(SNRind))) '_test.txt'];
    end
    fileID = fopen(fileName, 'r');
    
    sizeA = [12, Inf];
    A = fscanf(fileID, '%f %f %f %f %f %f %f %f %f %f %f %f', sizeA);
    fclose(fileID);
    
    A=A';
    [row, col] = size(A);
    det = 0;
    faldet = 0;
    
    for w = 1:row
        if A(w, 3) == 1
            if A(w,4) == 1
                det = det + 1;
            end
        else
            if A(w,4) == 1
                faldet = faldet + 1;
            end
        end
    end
    P_detection(SNRind) = 100*det / sum(A(:,3));
    P_false_alarm(SNRind) = 100*faldet / (wier - sum(A(:,3)));
end

figure
hold on
plot(SNR, P_detection, 'b', 'LineWidth', 1)
hold on
plot(SNR, P_false_alarm, 'r', 'LineWidth', 1)
ylim([0 100])
xlabel('SNR [dB]')
ylabel('Probability [%]')
legend('probability of detection', 'probability of false alarm');